In [1]:
from hypersurface import *
import sympy as sp
from pprint import pprint

In [18]:
z0, z1, z2, z3 = sp.symbols('z0, z1, z2, z3')
Z = [z0,z1,z2]
f = z0**3 + z1**3 + z2**3
HS = Hypersurface(Z, f, 100000)

In [19]:
k = 1
sections, ns = HS.get_sections(k)
H = np.identity(ns, dtype=int)

In [20]:
H_rand_pd = np.zeros((ns,ns))
while not np.all(np.linalg.eigvals(H_rand_pd) > 0):
    H_rand = np.random.rand(ns, ns)
    H_rand_pd = H_rand*H_rand.transpose()
integral = 0
for patch in HS.patches:
    for subpatch in patch.patches:
        sub_integral = subpatch.integrate(subpatch.get_FS_volume_form(H_rand_pd, k)/subpatch.get_FS_volume_form(H, k))
        #print(sub_integral)
        integral += sub_integral
print(integral/HS.n_points)
print(H_rand_pd)

(1.086905212306239+1.689021877459768e-20j)
[[0.59544604 0.02514675 0.26656481]
 [0.02514675 0.5180165  0.27112507]
 [0.26656481 0.27112507 0.38742014]]


In [21]:
H_rand_pd = np.zeros((ns,ns))
while not np.all(np.linalg.eigvals(H_rand_pd) > 0):
    H_rand = np.random.rand(ns, ns)
    H_rand_pd = H_rand*H_rand.transpose()
integral = 0
for patch in HS.patches:
    for subpatch in patch.patches:
        sub_integral = subpatch.integrate(subpatch.get_FS_volume_form(H_rand_pd, k)/subpatch.get_FS_volume_form(H, k))
        #print(sub_integral)
        integral += sub_integral
print(integral/HS.n_points)
print(H_rand_pd)

(1.0254070716905679-4.822547766966896e-20j)
[[0.20392258 0.01170788 0.06168397]
 [0.01170788 0.15667063 0.04707041]
 [0.06168397 0.04707041 0.10693961]]


In [22]:
H_rand_pd = np.zeros((ns,ns))
while not np.all(np.linalg.eigvals(H_rand_pd) > 0):
    H_rand = np.random.rand(ns, ns)
    H_rand_pd = H_rand*H_rand.transpose()
integral = 0
for patch in HS.patches:
    for subpatch in patch.patches:
        sub_integral = subpatch.integrate(subpatch.get_FS_volume_form(H_rand_pd, k)/subpatch.get_FS_volume_form(H, k))
        #print(sub_integral)
        integral += sub_integral
print(integral/HS.n_points)
print(H_rand_pd)

(0.988820662699416-6.591922221735839e-20j)
[[0.84951288 0.42377475 0.01138165]
 [0.42377475 0.45726232 0.04125805]
 [0.01138165 0.04125805 0.06917177]]


In [25]:
H_rand_pd = np.zeros((ns,ns))
while not np.all(np.linalg.eigvals(H_rand_pd) > 0):
    H_rand = np.random.rand(ns, ns)
    H_rand_pd = H_rand*H_rand.transpose()
integral = 0
for patch in HS.patches:
    for subpatch in patch.patches:
        sub_integral = subpatch.integrate(subpatch.get_FS_volume_form(H_rand_pd, k)/subpatch.get_FS_volume_form(H, k))
        #print(sub_integral)
        integral += sub_integral
print(integral/HS.n_points)
print(H_rand_pd)

(1.0170527612589928-3.3590970655925935e-20j)
[[0.37003881 0.22566036 0.11557159]
 [0.22566036 0.70946666 0.16280907]
 [0.11557159 0.16280907 0.64176806]]
