In [1]:
from hypersurface_tf import *
import sympy as sp
from pprint import pprint
import time
from sympy.utilities.autowrap import ufuncify

In [2]:
z0, z1, z2, z3 = sp.symbols('z0, z1, z2, z3')
Z = [z0,z1,z2,z3]
f = z0**4 + z1**4 + z2**4 + z3**4
HS = Hypersurface(Z, f, 100)

In [3]:
k = 4
sections, ns = HS.get_sections(k)
H = np.identity(ns, dtype=int)

In [4]:
def generate_H(ns):
    H_rand = np.random.rand(ns, ns)
    H_rand_pd = np.dot(H_rand, H_rand.transpose())
    return H_rand_pd

In [5]:
H_rand_pd = generate_H(ns)
#HS.integrate(lambda x: x.get_FS_volume_form('identity', k),holomorphic=True)
start_time = time.time()
#f = sp.lambdify(Z, HS.patches[0].patches[0].kahler_metric('symbolic',k))
#f = sp.lambdify(Z, HS.patches[0].patches[0].get_FS_volume_form(H_rand_pd, k))
f = ufuncify((z0,z1,z2,z3), HS.patches[0].patches[0].get_FS_volume_form(H_rand_pd, k))
end_time = time.time()
print(end_time - start_time)
#print(H_rand_pd)

KeyboardInterrupt: 

In [6]:
f = ufuncify(z0, z0.conjugate())

ImportError: dlopen(/private/var/folders/5s/mnmy7d_n79q3zxvyy_m2svwr0000gn/T/tmpqbprmvu0_sympy_compile/wrapper_module_0.cpython-37m-darwin.so, 2): Symbol not found: _conjugate
  Referenced from: /private/var/folders/5s/mnmy7d_n79q3zxvyy_m2svwr0000gn/T/tmpqbprmvu0_sympy_compile/wrapper_module_0.cpython-37m-darwin.so
  Expected in: flat namespace
 in /private/var/folders/5s/mnmy7d_n79q3zxvyy_m2svwr0000gn/T/tmpqbprmvu0_sympy_compile/wrapper_module_0.cpython-37m-darwin.so

In [7]:
HS.integrate(lambda x: x.omega_omegabar, holomorphic=True)

mpc(real='12.83918003712907', imag='2.4389427623089744e-19')

In [4]:
eta = lambda x: x.get_FS_volume_form('identity', k)/x.omega_omegabar

In [5]:
HS.integrate(lambda x: np.absolute(eta(x)), holomorphic=True)

(0.01010584799275301+1.1749973775531465e-21j)

In [6]:
k = 2

In [7]:
HS.integrate(lambda x: x.get_FS_volume_form('identity', k),holomorphic=True)

(0.4842830953176302-4.5449253452893146e-20j)

In [8]:
HS.integrate(lambda x: x.omega_omegabar, holomorphic=True)

(12.838668255763173+2.835078832085028e-19j)

In [9]:
eta = lambda x: x.get_FS_volume_form('identity', k)/x.omega_omegabar
HS.integrate(lambda x: np.absolute(eta(x)), holomorphic=True)

(0.04082341960758129+8.728408305014712e-22j)

In [11]:
z0, z1, z2 = sp.symbols('z0, z1, z2')
Z = [z0,z1,z2]
f = z0**3 + z1**3 + z2**3
HS = Hypersurface(Z, f, 10000)

In [19]:
k = 2

In [20]:
factor = HS.integrate(lambda x: x.omega_omegabar, holomorphic=True) / HS.integrate(lambda x: x.get_FS_volume_form('identity', k),holomorphic=True)

In [21]:
factor

(9.050281088109449-3.689916727764987e-19j)

In [22]:
eta = lambda x: x.get_FS_volume_form('identity', k)/x.omega_omegabar
HS.integrate(lambda x: np.absolute(eta(x)) * factor.real, holomorphic=True)

(1.0708270459795437+1.503682892880462e-19j)

In [22]:
H_rand_pd = generate_H(ns)
HS.integrate(lambda x: x.get_FS_volume_form(H_rand_pd, k)/x.get_FS_volume_form(H, k))
print(H_rand_pd)

(0.988820662699416-6.591922221735839e-20j)
[[0.84951288 0.42377475 0.01138165]
 [0.42377475 0.45726232 0.04125805]
 [0.01138165 0.04125805 0.06917177]]


In [25]:
H_rand_pd = generate_H(ns)
HS.integrate(lambda x: x.get_FS_volume_form(H_rand_pd, k)/x.get_FS_volume_form(H, k))
print(H_rand_pd)

(1.0170527612589928-3.3590970655925935e-20j)
[[0.37003881 0.22566036 0.11557159]
 [0.22566036 0.70946666 0.16280907]
 [0.11557159 0.16280907 0.64176806]]


In [27]:
z0, z1, z2, z3 = sp.symbols('z0, z1, z2, z3')
Z = [z0,z1,z2,z3]
f = z0**4 + z1**4 + z2**4 + z3**4
HS = Hypersurface(Z, f, 1000)

In [29]:
k = 1
sections, ns = HS.get_sections(k)
H = np.identity(ns, dtype=int)

In [30]:
H_rand_pd = generate_H(ns)
HS.integrate(lambda x: x.get_FS_volume_form(H_rand_pd, k)/x.get_FS_volume_form(H, k))
print(H_rand_pd)

(0.9923140229658463+2.038970196072439e-18j)
[[0.43025112 0.28831487 0.00099719 0.05764704]
 [0.28831487 0.97910786 0.47782184 0.46404444]
 [0.00099719 0.47782184 0.46867541 0.03041028]
 [0.05764704 0.46404444 0.03041028 0.80998043]]


In [31]:
H_rand_pd = generate_H(ns)
HS.integrate(lambda x: x.get_FS_volume_form(H_rand_pd, k)/x.get_FS_volume_form(H, k))
print(H_rand_pd)

(0.9701652886326646+2.9124204221432305e-18j)
[[0.07482128 0.06086188 0.18905865 0.06174087]
 [0.06086188 0.97180802 0.43852295 0.23956995]
 [0.18905865 0.43852295 0.87596711 0.13240882]
 [0.06174087 0.23956995 0.13240882 0.48924656]]


In [32]:
H_rand_pd = generate_H(ns)
HS.integrate(lambda x: x.get_FS_volume_form(H_rand_pd, k)/x.get_FS_volume_form(H, k))
print(H_rand_pd)

(0.9979734931607865+5.118223304268211e-18j)
[[0.17780888 0.04841297 0.00360587 0.14197116]
 [0.04841297 0.49237804 0.00623981 0.20315417]
 [0.00360587 0.00623981 0.15258133 0.06668826]
 [0.14197116 0.20315417 0.06668826 0.31902368]]


In [33]:
H_rand_pd = generate_H(ns)
HS.integrate(lambda x: x.get_FS_volume_form(H_rand_pd, k)/x.get_FS_volume_form(H, k))
print(H_rand_pd)

(1.0165898213125935+1.0936832034449472e-18j)
[[0.84382523 0.00456341 0.32261681 0.00565267]
 [0.00456341 0.40091798 0.15151979 0.13646535]
 [0.32261681 0.15151979 0.55220088 0.19863786]
 [0.00565267 0.13646535 0.19863786 0.44227972]]
