In [1]:
from hypersurface import *
import sympy as sp
from pprint import pprint
import time
import math
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [2]:
z0, z1, z2, z3, z4= sp.symbols('z0, z1, z2, z3, z4')
Z = [z0,z1,z2,z3]
f = z0**4 + z1**4 + z2**4 + z3**4
HS = Hypersurface(Z, f, 100)

In [4]:
k = 1
eta = lambda x: x.get_FS_volume_form('identity', k)/x.get_omega_omegabar()
start_time = time.time()
print(HS.integrate(lambda patch: np.absolute(eta(patch)), holomorphic=True))
print(time.time() - start_time)

(1.4095815516163843+3.430283465928883e-20j)
11.390451908111572


In [5]:
HS.set_k(1)

In [6]:
start_time = time.time()
inte = HS.integrate(lambda patch, point: np.absolute(patch.num_eta('identity', point)), holomorphic=True, numerical=True)
print(inte)
print(time.time()-start_time)

(1.4095815516163843-2.96890929484165e-19j)
92.35715198516846


In [3]:
k = 2
eta = lambda x: x.get_FS_volume_form('identity', k)/x.get_omega_omegabar()
start_time = time.time()
print(HS.integrate(lambda patch: np.absolute(eta(patch)), holomorphic=True))
print(time.time() - start_time)

(5.569253445491119+1.3981356333349765e-18j)
13.993659973144531


In [4]:
HS.set_k(2)
start_time = time.time()
inte = HS.integrate(lambda patch, point: np.absolute(patch.num_eta('identity', point)), holomorphic=True, numerical=True)
print(inte)
print(time.time()-start_time)

(5.569253445491119+4.7032647456861104e-18j)
89.29443264007568


In [3]:
k = 3
eta = lambda x: x.get_FS_volume_form('identity', k)/x.get_omega_omegabar()
start_time = time.time()
print(HS.integrate(lambda patch: np.absolute(eta(patch)), holomorphic=True))
print(time.time() - start_time)

(13.089748216152755-1.0635007031941387e-17j)
18.35923194885254


In [4]:
HS.set_k(3)
start_time = time.time()
inte = HS.integrate(lambda patch, point: np.absolute(patch.num_eta('identity', point)), holomorphic=True, numerical=True)
print(inte)
print(time.time()-start_time)

(13.089748216152753-1.4160042873971222e-17j)
88.34115624427795


In [7]:
func = sp.lambdify(patch.coordinates, patch.kahler_metric('identity',1))
pprint(func(*point))

array([[ 0.24, -0.08,  0.  , -0.08],
       [-0.08,  0.36,  0.  , -0.04],
       [ 0.  ,  0.  ,  0.4 ,  0.  ],
       [-0.08, -0.04,  0.  ,  0.36]])


In [8]:
#start_time = time.time()
#patch.num_FS_volume_form('identity', point)
patch.num_kahler_metric('identity', point)
#print(time.time() - start_time)

array([[ 0.24, -0.08,  0.  , -0.08],
       [-0.08,  0.36,  0.  , -0.04],
       [ 0.  ,  0.  ,  0.4 ,  0.  ],
       [-0.08, -0.04,  0.  ,  0.36]])

In [18]:
patch.sections_jacobian(z0,z1,z2,z3,z4)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [12]:
patch.sections(z0,z1,z2,z3,z4)

[z0, z1, z2, z3, z4]

In [20]:
np.conj([[1,1],[1,complex(0,1)]])

array([[1.-0.j, 1.-0.j],
       [1.-0.j, 0.-1.j]])

In [22]:
test = np.array([[1,1],[2,2]])

In [23]:
test * 2

array([[2, 2],
       [4, 4]])

In [24]:
test ** 2

array([[1, 1],
       [4, 4]])

In [9]:
b = np.array([0,complex(1,1),0])

In [10]:
b**2

array([0.+0.j, 0.+2.j, 0.+0.j])

In [13]:
sum(np.absolute(b)**2)

2.0000000000000004

In [23]:
np.matmul(b.reshape(4,1), b.reshape(4,1).T)

array([[1, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 1]])

In [11]:
np.matmul(b.T,b)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [19]:
b = np.array([1,1,1])

In [22]:
b.reshape(-1,1).T

array([[1, 1, 1]])

In [14]:
func = sp.lambdify([z0,z1,z2], (z0**2+z1**2+z2**2)/(z0*z1*z2 + z0**3 - z1**7))

In [16]:
start_time = time.time()
func(z0, z1, z2)
print(time.time() - start_time)

0.00019025802612304688


In [18]:
start_time = time.time()
func(1,4,3)
print(time.time() - start_time)

9.894371032714844e-05


In [32]:
func_new = sp.lambdify([z0,z1,z2,z3,z4], 1)

In [35]:
start_time = time.time()
func_new(0,0,0,2,4)
print(time.time() - start_time)

7.486343383789062e-05


In [38]:
def h(a, b):
    return a + b

In [42]:
def f(a):
    def g(b):
        return h(a, b)
    return g

In [39]:
h(1,2)

3

In [45]:
f(h_matrix)(patch)(point)

TypeError: f() missing 1 required positional argument: 'a'

In [9]:
def h(a, *b):
    for c in b:
        print (a + c)

In [11]:
h(1, 1, 2, 3)

2
3
4
