In [8]:
from hypersurface import *
import sympy as sp
import tensorflow as tf

In [9]:
z0, z1, z2, z3 = sp.symbols('z0, z1, z2, z3')
Z = [z0,z1,z2,z3]
f = z0**4 + z1**4 + z2**4 + z3**4
HS = Hypersurface(Z, f, 1000)

In [10]:
k = 1

In [11]:
y = lambda patch: patch.omega_omegabar/patch.get_FS_volume_form('identity', k)

In [12]:
patch = HS.patches[0].patches[0]

In [13]:
y_func = sp.lambdify(Z, y(patch))

In [19]:
y = [y_func(*point).real for point in patch.points]

Build a dataset

In [21]:
dataset = tf.data.Dataset.from_tensor_slices((patch.points, y))

In [22]:
dataset

<TensorSliceDataset shapes: ((4,), ()), types: (tf.complex128, tf.float64)>

In [23]:
tf.convert_to_tensor(patch.points)

<tf.Tensor: shape=(327, 4), dtype=complex128, numpy=
array([[ 1.00000000e+00+0.j        , -7.02924837e-01-0.70935854j,
         1.86168366e-01-0.34401408j,  2.62570447e-01-0.04733779j],
       [ 1.00000000e+00+0.j        ,  5.32173007e-01-0.71334768j,
        -7.06130540e-01+0.516737j  ,  2.77418846e-01-0.05651617j],
       [ 1.00000000e+00+0.j        , -5.85532167e-01-0.63692256j,
         5.51402906e-01-0.61132197j, -2.12678364e-01+0.00578141j],
       ...,
       [ 1.00000000e+00-0.j        ,  7.08605463e-01-0.66851049j,
         1.19003396e-02-0.70838729j, -5.16384733e-01+0.58268909j],
       [ 1.00000000e+00-0.j        ,  6.50067416e-01-0.64115969j,
         5.17843837e-01-0.53352905j,  7.55816095e-02-0.15948554j],
       [ 1.00000000e+00+0.j        , -7.04872911e-01+0.70696611j,
        -8.98049241e-07-0.32365616j,  2.39455162e-01+0.28141204j]])>

In [24]:
tf.convert_to_tensor(y)

<tf.Tensor: shape=(327,), dtype=float64, numpy=
array([ 88.80993213,  31.55879529,  56.68023461,  88.43017958,
        96.99340546, 108.08373405, 219.09435535,  95.57192592,
       144.45576343, 110.01940039,  90.71325401,  94.62926336,
        95.84579125,  77.44037   ,  13.27758808,  42.07560299,
       159.34772177,  93.79421725, 130.20854942, 143.39328126,
        68.64538522, 107.21951237, 191.9966556 ,  95.32796265,
        77.12296971,  28.25864012,  45.49852782,  61.56065243,
        28.34047004,  97.36161433, 181.58270243,  86.32022504,
        83.83267809,  72.64590816, 142.77279267,  54.14651079,
       154.93130165,  87.59597141,  86.10289361,  77.84899066,
        94.20545637,  94.04648918,  83.1591807 , 106.79880247,
        74.50317783, 114.22812744, 107.75814562, 104.16185621,
        78.13367549,  78.79311571,  35.75643174,  27.93247458,
       119.10081292, 115.66551879, 119.66548164, 134.16582942,
       100.20273362, 135.04235157, 176.04141911,  83.38491798,
       